### ISSUE TITLE
Client side error after deploying device

### ISSUE THREAD

**Issue by zinkkrysty** [topology-gg/isaac-working-view#30]
```
Cannot convert undefined or null to object
at Function.keys (<anonymous>)
```

Needs to be reproduced in development to get more details.

![image](https://user-images.githubusercontent.com/570771/185736191-497211f1-6e1f-4190-b101-6c2cb3dd36f5.png)

**Comment by guiltygyoza** [comment]
not seeing this anymore.

**Comment by zinkkrysty** [comment]
Yeah we can close it 👍
